server:
  port: 8082
spring:
  mvc:
    view:
      prefix: /
      suffix: .html

# nacos 配置中心
nacos:
  discovery:
    server-addr: 192.168.10.101:8848

# Dubbo 广播方式配置，如果调用不稳定可以修改为直连模式：https://gitcode.net/KnowledgePlanet/Lottery/-/issues/1
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  #    parameters:
  #      unicast: false
  registry:
    #    address: N/A
    #    address: #multicast://224.5.6.7:1234
    #    address: zookeeper://127.0.0.1:2181
    address: nacos://192.168.10.101:8848
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: cn.itedus.lottery.rpc.*

